CREATE DATABASE IF NOT EXISTS `nodelogin` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `nodelogin`;

CREATE TABLE IF NOT EXISTS `accounts` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `username` varchar(50) NOT NULL,
    `password` varchar(225) NOT NULL,
    `email` varchar(100) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP DATABASE IF EXISTS `clippy_bird`;
CREATE DATABASE `clippy_bird`;
USE `clippy_bird`;

CREATE TABLE IF NOT EXISTS `IMAGE` (
    `IMAGE_ID` BIGINT NOT NULL,
    `USER_ID` VARCHAR(50) NOT NULL,
    `FILE_LOCATION` VARCHAR(255) NOT NULL,
    `DATE_TIME` DATETIME,
    `IMAGE_LOCATION` VARCHAR(255),
    `IMAGE_NAME` VARCHAR(255),
    `SPECIES` VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS `USER` (
    `USER_ID` VARCHAR(50) NOT NULL,
    `FIRST_NAME` VARCHAR(50) NOT NULL,
    `LAST_NAME` VARCHAR(50) NOT NULL,
    `EMAIL` VARCHAR(100) NOT NULL,
    `PHONE` VARCHAR(15),
    `PASSWORD` VARCHAR(100) NOT NULL
);
