DROP DATABASE IF EXISTS `clippy_bird`;
CREATE DATABASE `clippy_bird`;
USE `clippy_bird`;

<<<<<<< HEAD
CREATE TABLE IF NOT EXISTS `IMAGE` (
    `IMAGE_ID` BIGINT NOT NULL,
    `USER_ID` VARCHAR(50) NOT NULL,
    `FILE_LOCATION` VARCHAR(255) NOT NULL,
    `DATE_TIME` DATETIME,
    `IMAGE_LOCATION` VARCHAR(255),
    `IMAGE_NAME` VARCHAR(255),
    `SPECIES` VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS `USER` (
    `USER_ID` INT AUTO_INCREMENT PRIMARY KEY,
    `USER_ID` VARCHAR(50) NOT NULL,
    `FIRST_NAME` VARCHAR(50) NOT NULL,
    `LAST_NAME` VARCHAR(50) NOT NULL,
    `EMAIL` VARCHAR(100) NOT NULL,
    `PHONE` VARCHAR(15),
    `PASSWORD` VARCHAR(100) NOT NULL
=======

CREATE TABLE IMAGE (
    IMAGE_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(50) NOT NULL,
    FILE_LOCATION VARCHAR(255) NOT NULL,
    DATE_TIME DATETIME,
    IMAGE_LOCATION VARCHAR(255),
    IMAGE_NAME VARCHAR(255),
    SPECIES VARCHAR(50)
);

CREATE TABLE USER (
    USER_ID VARCHAR(50) NOT NULL PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PHONE VARCHAR(15),
    PASSWORD VARCHAR(100) NOT NULL
>>>>>>> main
);


